package com.study.ai.agent.tool;

import com.study.common.BusinessException;
import com.study.dto.request.GenerateResourcePackageRequest;
import com.study.dto.vo.ResourceAssetVO;
import com.study.entity.LearningMaterial;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Component
public class SafetyTools {

    /**
     * Validates that at least one resource type is selected.
     *
     * @param request resource package request
     */
    public void validateSelectedResources(GenerateResourcePackageRequest request) {
        if (!enabled(request.getIncludeSummary())
                && !enabled(request.getIncludeMindMap())
                && !enabled(request.getIncludeQuiz())
                && !enabled(request.getIncludePlan())
                && !enabled(request.getIncludeMultimodalScript())) {
            throw new BusinessException(400, "至少选择一种资源类型");
        }
    }

    private boolean enabled(Boolean value) {
        return value == null || Boolean.TRUE.equals(value);
    }

    /**
     * Builds deterministic quality and safety notes for the generated package.
     *
     * <p>当多模态资产存在失败项时，追加 {@code multimodalFailures} 说明，
     * 提示用户检查讯飞配置或内容审核（spec §8.4 失败容忍）。
     *
     * @param material material entity
     * @param resources generated resource map
     * @param assets multimodal assets (audio/image) generated by MultimodalAgent
     * @return quality check map
     */
    public Map<String, Object> buildQualityChecks(LearningMaterial material,
                                                   Map<String, Object> resources,
                                                   List<ResourceAssetVO> assets) {
        Map<String, Object> checks = new HashMap<>();
        checks.put("materialReady", true);
        checks.put("materialId", material.getId());
        checks.put("grounding", "资源内容基于当前用户已处理完成的学习资料生成，并围绕讲解、导图、练习和学习路径进行组织");
        checks.put("resourceCount", resources.size());
        checks.put("multimodalMode", resources.containsKey("multimodalScript") ? "script_package" : "not_requested");
        checks.put("safety", "系统已完成资料归属校验、参数校验和结构化输出约束，生成内容用于学习参考，建议结合原始资料复核关键概念");

        if (assets != null && !assets.isEmpty()) {
            long audioFailed = assets.stream()
                    .filter(a -> "audio".equalsIgnoreCase(a.getAssetType()))
                    .filter(a -> "failed".equalsIgnoreCase(a.getStatus()))
                    .count();
            long imageFailed = assets.stream()
                    .filter(a -> "image".equalsIgnoreCase(a.getAssetType()))
                    .filter(a -> "failed".equalsIgnoreCase(a.getStatus()))
                    .count();
            long totalFailed = audioFailed + imageFailed;
            if (totalFailed > 0) {
                List<String> details = new ArrayList<>();
                if (audioFailed > 0) {
                    details.add("播客音频生成失败 " + audioFailed + " 个，请检查讯飞 TTS 配置或文本内容");
                }
                if (imageFailed > 0) {
                    details.add("知识配图生成失败 " + imageFailed + " 个，请检查讯飞文生图配置或提示词是否触发内容审核");
                }
                Map<String, Object> multimodalFailures = new HashMap<>();
                multimodalFailures.put("totalFailed", totalFailed);
                multimodalFailures.put("details", details);
                multimodalFailures.put("suggestion", "多模态资产生成失败，需要检查讯飞配置或内容审核");
                checks.put("multimodalFailures", multimodalFailures);
            }
        }
        return checks;
    }

    /**
     * Builds learner-facing notes for resource package review and exports.
     *
     * @param resources generated resource map
     * @return presentation note list
     */
    public List<String> buildPresentationNotes(Map<String, Object> resources) {
        List<String> notes = new ArrayList<>();
        notes.add("资源工坊已将当前课程资料整理为讲解、导图、练习和路径一体化的学习资源包。");
        notes.add("生成过程保留了各阶段处理记录，便于回看资源来源、生成步骤和内容状态。");
        if (resources.containsKey("multimodalScript")) {
            notes.add("多模态资源为课程内容补充了音频讲解、图像提示和微课脚本等表达形式。");
        }
        notes.add("历史资源包可随时恢复查看，生成结果也可以导出为 Markdown 或 PDF 继续复习。");
        return notes;
    }
}
